#!/usr/bin/env python
# encoding: utf-8
"""
test_cctop_orders.py

Created by Maximillian Dornseif on 2008-08-29.
Copyright (c) 2008 HUDORA. All rights reserved.
"""

import datetime
import unittest
import os.path
from decimal import Decimal
import edilib.cctop.orders


class ParsingTestsuite(unittest.TestCase):
    """Test for records generated by generate_field_datensatz_class()"""
    
    def test_basic_tru(self):
        """Basic parsing functionality."""
        
        # Testdaten, die wir von Stratedi erhalten haben.
        data = open(os.path.join(os.path.dirname(__file__), 'orders_tru.txt')).read()
        parsed = edilib.cctop.orders.parse_rawdata(data)
        self.assertEqual(parsed, (None,
 [{'abschlaege': [{'art': u'GRB',
                   'name': u'EXPANSIONS BONUS',
                   'prozent': Decimal("1.00")},
                  {'art': u'RCH', 'name': u'', 'prozent': Decimal("1.00")}],
   'bestelldatum': datetime.datetime(2008, 4, 15, 0, 0),
   'bestelltext': u'Achtung!! Auftragskopie des Originalauftrages - EDI\nLIEFERUNG ERFOLGT: FREI HAUS, VERSICHERT UND VERSTEUERT\nALLE TRANSPORTE MUESSEN DEN RAHMENBEDINGUNGEN FUER DEN WARENVERKEHR MIT KUNDENNAM, NEUESTE AUSGABE, ENTSPRECHEN.\nDIE NICHTBEACHTUNG DER RAHMENBEDINGUNGEN KANN ZUR ANNAHME VERWEIGERUNG DER WARE FUEHREN. ALLE KOSTEN, DIE DURCH DIE NICHTBEACHTUNG ENTSTEHEN, TRAEGT DER HERSTELLER.',
   'kundenauftragsnr': u'3101586145',
   'lieferadresse': {'fax': u'',
                     'iln': u'4005998000007',
                     'land': u'',
                     'name1': u'NIEDERLASSUNGSNAME ABC',
                     'name2': u'',
                     'name3': u'',
                     'ort': u'HANSE',
                     'plz': u'',
                     'strasse': 'AM GLUESTIEG 5',
                     'tel': u'',
                     'ustdid': u''},
   'positionen': [{'anlieferdatum_max': datetime.datetime(2008, 10, 4, 0, 0),
                   'anlieferdatum_min': datetime.datetime(2008, 9, 28, 0, 0),
                   'artnr': u'71590TR',
                   'ean': u'4005998715901',
                   'kundenartnr': u'165816',
                   'menge': 80,
                   'menge_kartons': u'6',
                   'name': u'BASEBALL GROESSE DREI ***+',
                   'positionsnr': u'1',
                   'preis': u'88.4300'}],
   'rechnungsadresse': {'fax': u'',
                        'iln': u'4005998000007',
                        'land': u'',
                        'name1': u'',
                        'name2': u'',
                        'name3': u'',
                        'ort': u'',
                        'plz': u'',
                        'strasse': '',
                        'tel': u'',
                        'ustdid': u''},
   'skontoprozent': Decimal("45.6700"),
   'skontotage': u'123'}]))

        
if __name__ == '__main__':
    unittest.main()
